user nginx;
worker_processes 2;
worker_rlimit_nofile 2048;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server_tokens off;
    client_body_buffer_size 16k;

    server {
        listen 80;
        server_name localhost;

        http2 on;

        client_max_body_size 10m;
    }
}